version: '3.8'

x-common-variables: &common-variables
  POSTGRES_DB: SISTEMA_EDUCATIVO
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root

services:
  psql_app:
    image: postgres
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables

      
  nginx:
    container_name: nginx_container
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    container_name: api_container
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - psql_app
    volumes:
      - /app/node_modules
      - ./server:/app
    
  client:
    container_name: client_container
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    

  adminer:
    container_name: adminer_container
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - psql_app
    environment:
      ADMINER_DEFAULT_SERVER: psql_app

  